name: Dummy Workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000033@ds.study.iitm.ac.in
        run: echo "This step does absolutely nothing useful."
